package gs1demo;

import java.io.*;
import java.awt.*;
import java.awt.image.*;
import javax.swing.*;

// |...:: [ ------------------- ] ::... |
import com.idautomation.databar.*;
import com.idautomation.databar.encoder.*;

// |...:: [ ------------------- ] ::... |
import com.idautomation.linear.*;
import com.idautomation.linear.encoder.*;
import javax.imageio.ImageIO;
import org.krysalis.barcode4j.output.bitmap.BitmapCanvasProvider;

/**
 *
 * @author Administrador
 */
public class prueba extends javax.swing.JFrame {

    DataBar bc1;
    BufferedImage image1;

    // |...:: [ ------------------- ] ::... |
    BarCode bc2;
    BufferedImage image2;

    /**
     * Creates new form prueba
     */
    public prueba() {
        initComponents();
        this.setTitle("PRUEBA DE CODIGO DE BARRA ");
        // |...:: [ ------------------- ] ::... |
        // |...:: [    LINEAR BARCODE   ] ::... |
        // |...:: [ ------------------- ] ::... |

        bc2 = new BarCode();
        bc2.barType = bc2.CODE128;

        bc2.setDataToEncode("4157419700003137390200000080009620200716802000002237041022020");
        
        bc2.setSize(400, 200);

        image2 = new BufferedImage(400, 400, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = image2.createGraphics();
        bc2.paint(g2);

        ImageIcon imagen2 = new ImageIcon(image2);
        Icon icono2 = new ImageIcon(imagen2.getImage().getScaledInstance(jLabelLogo2.getWidth(), jLabelLogo2.getHeight(), Image.SCALE_DEFAULT));
        jLabelLogo2.setSize(icono2.getIconWidth() + 10, icono2.getIconHeight() + 40);
        jLabelLogo2.setIcon(icono2);
        this.repaint();

        try {
            // Get icon from label
            ImageIcon icon = (ImageIcon) jLabelLogo2.getIcon();
            // Copy image
            BufferedImage image = new BufferedImage(icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_RGB);
            Graphics2D g3 = image.createGraphics();
            g3.drawImage(icon.getImage(), 0, 0, icon.getImageObserver());
            g3.dispose();
            BufferedImage dest = image.getSubimage(0, 13, 825, 40);
            ImageIO.write(dest, "jpg", new File("C:\\Users\\Administrador.ARRUPE\\Desktop\\barcode\\GS1.jpg"));

        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo1 = new javax.swing.JLabel();
        jLabelLogo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelLogo2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelLogo2, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLogo2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JLabel jLabelLogo2;
    // End of variables declaration//GEN-END:variables
}
